version: '3'
services:
    mariadb:
        restart: unless-stopped
        image: 'mariadb:10'
        ports:
            - '127.0.0.1:3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'overnites'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
        volumes:
            - 'mariadb:/var/lib/mysql'
        networks:
            - network
    nginx:
        restart: unless-stopped
        image: 'nginx:1.23'
        ports:
            - '80:80'
            - '443:443'
        networks:
            - network
        volumes:
            - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
    astro:
        restart: unless-stopped
        build:
            context: './web'
            dockerfile: 'Dockerfile'
        networks:
            - network
    fastify:
        restart: unless-stopped
        build:
            context: './api'
            dockerfile: 'Dockerfile'
        networks:
            - network
networks:
    network:
        driver: bridge
volumes:
    mariadb:
        driver: local
