version: '3'
services:
    nginx:
        restart: unless-stopped
        image: 'nginx:1.23'
        ports:
            - '80:80'
            - '443:443'
        networks:
            - network
        volumes:
            - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
        depends_on:
            - astro
            - fastify
    redis:
        image: redis:7.0-bullseye
        restart: always
        ports:
        - '127.0.0.1:6379:6379'
        command: redis-server --loglevel warning
    astro:
        restart: unless-stopped
        build:
            context: './web'
            dockerfile: 'Dockerfile'
        networks:
            - network
        depends_on:
            - fastify
    fastify:
        restart: unless-stopped
        build:
            context: './api'
            dockerfile: 'Dockerfile'
        networks:
            - network
        depends_on:
            - redis
networks:
    network:
        driver: bridge
